---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backdeploy
spec:
  selector:
    matchLabels:
      app: vinology
      service: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: vinology
        service: backend
    spec:
      containers:
        - name: vinology-server
          image: ccdaniele/vinology-server:1.2.1
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "300m"
          ports:
            - name: http
              containerPort: 3000