apiVersion: v1
kind: Service
metadata:
  name: frontservice
spec:
  selector:
    app: vinilogy
    service: frontend
  type: NodePort
  ports:
  - nodePort: 31341
    port: 3001
    protocol: TCP
    targetPort: 3001
status:
  loadBalancer: {}