apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontdeploy
spec:
  selector:
    matchLabels:
      app: vinilogy
      service: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: vinilogy
        service: frontend
    spec:
      containers:
      - name: vinclient
        image: ccdaniele/vin-client:v1.0.2_full_env
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
          limits:
            memory: "200Mi"
            cpu: "600m"      
        ports:
        - containerPort: 3001
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP


