apiVersion: v1
kind: Pod
metadata:
  name: vinology-client
  labels:
    app: client
spec:
      containers:
      ## container react app
      - name: vinology-client
        image: ccdaniele/vin-client:v.1.0.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "250m"      
        ports:
        - containerPort: 3001
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
