apiVersion: v1
kind: Pod
metadata:
  name: vinclient
  labels:
    app: client
spec:
      containers:
      - name: vinclient
        image: ccdaniele/vin-client:v1.0.2_full_env
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "250m"      
        ports:
        - containerPort: 3001
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
