apiVersion: v1
kind: Pod
metadata:
  name: vinserver
  labels:
    app: server
spec:
      containers: 
      - name: vinserver
        image: ccdaniele/vinology-server:1.2.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
          - containerPort: 3000
            name: server-port
